apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "fasit"
  namespace: "default"
  labels:
    team: "aura"
spec:
  # resources: # Optional. See: http://kubernetes.io/docs/user-guide/compute-resources/
  #   limits:
  #     cpu: "2" # app will have its cpu usage throttled if exceeding this limit
  #     memory: 2Gi  # app will be killed if exceeding these limits
  #   requests: # App is guaranteed the requested resources and  will be scheduled on nodes with at least this amount of resources available
  #     cpu: "1"
  #     memory: 1Gi
  image: "docker.adeo.no:5000/fasit:IMAGE_VERSION"
  port: 8080
  replicas:
    min: 2
    max: 4
  liveness:
    path: "/conf/isalive"
    initialDelay: 90
    timeout: 2
  readiness:
    path: "/conf/isalive"
    initialDelay: 90
    timeout: 2
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - "https://fasit.nais.preprod.local/conf/"
    - "https://fasit.nais.preprod.local/api"
    - "https://fasit.nais.preprod.local/rest"
  cpuThresholdPercentage: 50
  env:
    - name: "LOG_OUTPUT"
      value: "JSON"
    - name: "ENVIRONMENT_NAME"
      value: "dev"
    - name: "ENVIRONMENT_CLASS"
      value: "u"
    - name: "ENVCONFDB_URL"
      value: "jdbc:oracle:thin:@d26dbfl022.test.local:1521/FASIT_CDU101"
    - name: "LDAP_USER_BASEDN"
      value: "ou=NAV,ou=BusinessUnits,dc=test,dc=local"
    - name: "LDAP_SERVICEUSER_BASEDN"
      value: "ou=ServiceAccounts,dc=test,dc=local"
    - name: "LDAP_DOMAIN"
      value: "TEST.LOCAL"
    - name: "LDAP_BASEDN"
      value: "dc=test,dc=local"
    - name: "LDAP_URL"
      value: "ldaps://ldapgw.test.local"
    - name: "VAULT_URL"
      value: "https://vault.adeo.no"
    - name: "BASTA_URL"
      value: "https://fjas.no/rest"
    - name: "ORACLE_V1_URL"
      value: "https://fjas.test.local/rest/v1/oracledb"
    - name: "DEPLOYLOG_V1_URL"
      value: "https://vera.nais.oera-q.local/api/v1/deploylog"
    - name: "ROLE_OPERATIONS_GROUPS"
      value: "0000-ga-env_config_L, 0000-GA-WAS_LOGGER-Test, 0000-GA-env-config-testAdmin,\
      \ 0000-GA-MOTTAK-WS, 0000-GA-Confluence"
    - name: "ROLE_SELFSERVICE_GROUPS"
      value: "0000-GA-STDAPPS"
    - name: "ROLE_PROD_OPERATIONS_GROUPS"
      value: "0000-ga-env_config_S, 0000-GA-Confluence"
    - name: "ROLE_SELFSERVICE_PROD_GROUPS"
      value: "TODO"
    - name: "ROLE_SUPERUSER_GROUPS"
      value: "0000-ga-fasit-superuser, 0000-ga-env_config_L"
    - name: "PUBLISH_DEPLOYMENT_EVENTS_TO_KAFKA"
      value: "true"
    - name: "KAFKA_SERVERS"
      value: "pkc-e0xg5.europe-north1.gcp.confluent.cloud:9092"
    - name: "KAFKA_SASL_ENABLED"
      value: "true"
    - name: "KAFKA_DEPLOYMENT_EVENT_TOPIC"
      value: "deployment-events-test"

  vault:
    enabled: true
    sidecar: true
    paths:
      - kvPath: "oracle/data/dev/creds/fasit_cdu101-user"
        mountPath: "/secrets/oracle/envconfDB"
      - kvPath: "serviceuser/data/test/srvssolinux"
        mountPath: "/secrets/ldap/ldap"
      - kvPath: "serviceuser/data/test/srvfasit"
        mountPath: "/secrets/credential/srvfasit"
      - kvPath: "certificate/data/dev/fasit-keystore"
        mountPath: "/secrets/certificate/fasit-keystore"
      - kvPath: "credential/data/dev/fasit_kafka_user"
        mountPath: "/secrets/credential/fasit.kafka.user"
